# Generated by Django 6.0 on 2025-12-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uplaod', '0006_auto_20191129_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
